spring.application.name=grafana

management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.tags.application=${spring.application.name}

management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]